# Generated by Django 5.2.7 on 2025-11-01 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_course_instructor_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='location',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', 'المستوى الأول'), ('200', 'المستوى الثاني'), ('300', 'المستوى الثالث'), ('400', 'المستوى الرابع')], default='100', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='registration',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Registered', 'مسجل'), ('Dropped', 'منسحب'), ('Completed', 'مكتمل'), ('Failed', 'فشل')], default='Registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.student'),
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SUN', 'الأحد'), ('MON', 'الإثنين'), ('TUE', 'الثلاثاء'), ('WED', 'الأربعاء'), ('THU', 'الخميس')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(default='G-101', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='academic.course')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('course', 'day_of_week', 'start_time')},
            },
        ),
    ]
